import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState, useEffect } from 'react'
import styles from '@/styles/Home.module.css'
import butter from '../img/butter.png'
import butterSound from '../mp3/butters.mp3'
import remix from '../mp3/remix.mp3'
import { Parallax, ParallaxLayer } from '@react-spring/parallax'

const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  const [setCount, setPlaying] = useState(0);
  const [audio, setAudio] = useState(null);
  const [initNum, setNum] = useState(Math.floor(Math.random() * 50));
  const [clicks, numClicks] = useState(0);

  function handleImageClick() {
    numClicks(clicks + 1);
    console.log("clicked");
    if (audio) {
      audio.pause();
    }
    const newAudio = new Audio();
    setPlaying(setCount+1);
    if (setCount == initNum) {
      newAudio.src = remix;
      setNum(Math.floor(Math.random() * 50));
      setPlaying(0);
    } else {
      newAudio.src = butterSound;  
    }
    newAudio.play();
    setAudio(newAudio);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="flex flex-col h-full">
          <Parallax pages={3} className="bg-yellow-300">
            <ParallaxLayer offset={0} factor={1} speed={2} className="bg-black">
              <div className="max-h-full mt-80 flex justify-center">
                <p className="font-bold text-8xl text-white">EXOTIC BUTTERS</p>
              </div>
            </ParallaxLayer>
            <ParallaxLayer offset={1} factor={0.3} speed={0.4}>
              <div className="max-h-full flex justify-center">
                <p className="text-orange-900 text-4xl font-bold">Paying tribute to exotic butters</p>
                <p className="text-orange-900 text-4xl font-bold"><br/>And yes, I know this site is stupid. I'm self-aware.</p>
              </div>
            </ParallaxLayer>
            <ParallaxLayer offset={1} speed={3}>
              <div className="max-h-full mt-28 flex justify-center">
                <div className="text-orange-900 text-9xl font-bold">{clicks} clicks dude</div>
              </div>
            </ParallaxLayer>
            <ParallaxLayer offset={2} sticky ={{start: 2}} className="bg-black">
              <div className="flex max-h-full mt-60 justify-center">
                <Image src={butter} onClick={handleImageClick} alt="exotic butters" width='500' height='500'/>
              </div>
            </ParallaxLayer>
          </Parallax>
        </main>
    </>
  )
}

export default Home;